//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesAutomationWebsite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>F|Per Folder</string>
  <string>S|Per Sector</string>
  <string>D|Per Duration</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FeeScopeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FeeScopeList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>-1</string>
  <string>1</string>
  <string>2</string>
  <string>4</string>
  <string>8</string>
  <string>12</string>
  <string>24</string>
  <string>48</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection HourList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["HourList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>1|Hotel Only</string>
  <string>2|Car Only</string>
  <string>3|Car or Hotel</string>
  <string>4|Car and Hotel</string>
  <string>5|Amendment Fee - Domestic Hotel</string>
  <string>6|Amendment Fee - TransTasman</string>
  <string>7|Amendment Fee - South Pacific</string>
  <string>8|Amendment Fee - LongHaul</string>
  <string>9|Charge Back - Domestic Car</string>
  <string>10|Charge Back - Domestic Hotel</string>
  <string>11|Nett Hotel Fee - Domestic</string>
  <string>12|Charge Back - Domestic Other</string>
  <string>13|Cancellation Fee - Domestic </string>
  <string>14|Nett Car Fee - Domestic</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection QueryTypeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["QueryTypeList"]));
            }
        }
    }
}
